wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    code_path: code/bloem/experiments/self-distill.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.16
    start_time: 1679676732.789095
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.9.16
      5: 0.13.11
      8:
      - 3
      - 5
attention_type:
  desc: null
  value: default
batch_size:
  desc: null
  value: 32
batches:
  desc: null
  value: 1000000
context:
  desc: null
  value: 512
data:
  desc: null
  value: null
debug:
  desc: null
  value: false
depth:
  desc: null
  value: 12
distill_with_target:
  desc: null
  value: true
distilltemp:
  desc: null
  value: 2.0
distpoint:
  desc: null
  value: 6
embedding:
  desc: null
  value: 768
enrich_loss:
  desc: null
  value: false
final:
  desc: null
  value: false
gamma:
  desc: null
  value: null
gradient_clipping:
  desc: null
  value: 1.0
lr:
  desc: null
  value: 0.0003
num_heads:
  desc: null
  value: 8
sample_length:
  desc: null
  value: 600
seed:
  desc: null
  value: 1
tags:
  desc: null
  value: null
tb_dir:
  desc: null
  value: ./runs
test_batchsize:
  desc: null
  value: 64
test_every:
  desc: null
  value: 1000
test_subset:
  desc: null
  value: 100000
val_batchsize:
  desc: null
  value: 128
warmup:
  desc: null
  value: 0
